// Build-time generator for the 3D "soycraft" wordmark.
// Converts the word into a single SVG path using a rounded font (Fredoka),
// which the game extrudes into 3D via THREE.SVGLoader at runtime.
//
// Run: node scripts/gen-logo.mjs
// Output: src/config/logoPath.js  (an SVG path string + viewBox)
//
// To change the wordmark or font: drop a different .ttf next to this script,
// update FONT / WORD below, and re-run.
import opentype from 'opentype.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT = join(__dirname, 'Fredoka600.ttf');
const WORD = 'soycraft';
const FONT_SIZE = 100;

const font = opentype.loadSync(FONT);
// y is baseline; we lay the text out at baseline = FONT_SIZE.
const path = font.getPath(WORD, 0, FONT_SIZE, FONT_SIZE);
const d = path.toPathData(3);

// Compute a tight bounding box so the game can center the logo.
const bb = path.getBoundingBox();
const out = {
  d,
  viewBox: { x1: bb.x1, y1: bb.y1, x2: bb.x2, y2: bb.y2 },
  width: bb.x2 - bb.x1,
  height: bb.y2 - bb.y1,
};

const js = `// AUTO-GENERATED by scripts/gen-logo.mjs — do not edit by hand.
// 3D "soycraft" wordmark outline (rounded font), extruded at runtime.
export const LOGO = ${JSON.stringify(out)};
`;
writeFileSync(join(__dirname, '..', 'src', 'config', 'logoPath.js'), js);
console.log('wrote src/config/logoPath.js  (path length', d.length, 'chars, bbox', out.width.toFixed(0), 'x', out.height.toFixed(0), ')');
